EmployeeManagementCore/ViewModels/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagementCore.ViewModels
{
    public class PostViewModel
    {
        [Key]
        public int post_id { get; set; }
        [Required]
        [Display(Name = "Create a post")]
        public string post { get; set; }
        public string post_data { get; set; }
        public string post_time { get; set; }
        public string user_id { get; set; }
    }
}

EmployeeManagementCore/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using DataAccess.Models;
using DataAccessWithRepository.Model;
using DataAccessWithRepository.Model.IRepository;
using EmployeeManagementCore.Utils;
using EmployeeManagementCore.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;

namespace EmployeeManagementCore.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostRepository postRepository;
        private readonly IHostingEnvironment environment;
        private readonly BugTriageContext context;
        private readonly UnitOfWork unitOfWork;

        public PostController(IPostRepository postRepository, IHostingEnvironment environment, BugTriageContext context)
        {
            this.postRepository = postRepository;
            this.environment = environment;
            this.unitOfWork = new UnitOfWork(context);
        }
       

        [Route("/")]
        public IActionResult Create()
        {
           
            return View();
        }
      
        public IActionResult ViewPosts()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(PostViewModel postData)
        {
            if (ModelState.IsValid) {
                Post posts = new Post
                {
                    post = postData.post,
                    post_data = DateTime.Now.ToString("dd/MM/yyyy"),
                    post_time = DateTime.Now.ToString("hh:tt:ss"),
                    user_id = postData.user_id

                };
                unitOfWork.Posts.Add(posts);
                unitOfWork.Complete();
            }
           
            return View(postData);
        }

        public IActionResult GetPost(int page=0, string query=null) {
            var posts=postRepository.GetPostWithComment(page, query);
            return Json(posts);
        }


    }
}

EmployeeManagementCore/Views/Post/Create.cshtml
@model EmployeeManagementCore.ViewModels.PostViewModel
@inject UserManager<IdentityUser> userManager
@{
    ViewData["Title"] = "Create";
}



<h4>Create Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Post" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="post" class="control-label"></label>
                <textarea asp-for="post" class="form-control"></textarea>
                <span asp-validation-for="post" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="post_id" />    
            <input type="hidden" asp-for="user_id" value="@userManager.GetUserId(User)" />

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EmployeeManagementCore/Views/Post/ViewPosts.cshtml
@{
    ViewData["Title"] = "ViewPosts";
}

<h2>ViewPosts</h2>

<div class="container">
    <div id="post">
        



    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" onclick="loadData(1)">1</a></li>
            <li class="page-item"><a class="page-link" onclick="loadData(2)">2</a></li>
            <li class="page-item"><a class="page-link" onclick="loadData(3)">3</a></li>
        </ul>
    </nav>
</div>
@section scripts{
    <script>
    $(document).ready(function () {
        $.ajax({
            url: "/Post/GetPost",
            type: "Get",
            data: { 'page': 1 },
            success(data) {
                loadPost(data);

            }

        })
    });
    function loadPost() {
        var post = "";

        $.each(data, function (i, val) {
            post += '   <div class="card">  ' +
                '           <div class="card-header">  ' +
                '               <h4>' + val.post + '</h4>  ';
            '              </div>  ';
            //var comment = "";
            $.each(val.comments, function (ind, comments) {
                post += '   <div class="card-body">  ' +
                    '               <p class="card-text" id="comment">' + comments.comment + '</p>  ' +
                    '               <button id="like_' + comment.comment_id + '">Like</button>  ' +
                    '               <button id="dislike_' + comment.comment_id + '">Dislike</button>  ' +
                    '     ' +
                    '          </div>  ';
            });
            post += '    <div class="row">  ' +
                '               <div class="col-md-2"> <textarea id="comment_box"></textarea></div>  ' +
                '               <div class="col-md-2"><button id="submit_comment">ok</button></div>  ' +
                '          </div>  ';
            '           </div>  ';

        });
        $('$post').html(post);
    }
    function loadData(page) {
        $.ajax({
            url: "/Post/GetPost",
            type: "Get",
            data: {'page':page},
            success(data) {
                loadPost(data);

            }

        })
    }
    </script>
}